### ISSUE TITLE
Reduce CSV payload size by using Mapcode

### ISSUE THREAD

**Issue by ckrey** [owntracks/gw#95]
http://www.mapcode.com

`VHDT2.TZJR`rather than `51.999987,-0.988065`

**Comment by ckrey** [comment]
mapcode-foundation/mapcode-java#9

**Comment by rijnb** [comment]
(Message from Mapcode project owner) We have implemented a Python version as well. You may wish to check it out at: https://github.com/mapcode-foundation/mapcode-python

We also recently reverted the Java language for the Java library from 8 back to 6, to accommodate Android users. That version has not been released officially, but if the tests run OK, it will be released shortly as 2.0.1.

The Python version will be updated to 2.0.0 as well shortly (it's based on the C version).
