### ISSUE TITLE
offUntil must cause device to go silent

### ISSUE THREAD

**Issue by jpmens** [owntracks/gw#96]
Setting `offUntil` in the future, currently is buggy: the device still *frequently* publishes `l`-type messages with the last time.

In addition, we have discussed that, when `offUntil` is set, it should also silence 

* trip
* cellinfo
* providerinfo
* GPIO
* obd2, FMS
* basically everything incl. start message

**Comment by jpmens** [comment]
Alarms should still be reported probably

**Comment by ckrey** [comment]
If offUntil is engaged, Greenwich will not transmit
- any location messages
- alarm message
- any voltage messages (might get info about start and stop engine from this)
- cellinfo message
- operatorlist message
- FMS or OBD2 messages

Still does send
- start message (version, IMEI and timestamp)
- $gps response with "no location available"
- debug messages which might contain private data
- output from commands via MQTT

Re Alarms:
What is the use case? Alarm is only activated when device is shutdown and motion is configured.

**Comment by jpmens** [comment]
Sounds good. (Forget the alarms; you're right.)

**Comment by ckrey** [comment]
If offUntil is engaged:
- lastFix is not stored/updated in settings when shutting down
- $state command response does not include CellInfo or Operators

**Comment by ckrey** [comment]
If offUntil is engaged:

$state command response does Voltage info

**Comment by ckrey** [comment]
If offUntil is engaged:

trip counter does not get updated
