### ISSUE TITLE
Is offUntil preventing setting date?

### ISSUE THREAD

**Issue by jpmens** [owntracks/gw#97]
As discussed regarding `K2`.

**Comment by jpmens** [comment]
The parameter was:

```
offUntil=1410180416
```

which corresponds do `Mon Sep  8 14:46:56 2014`

This is illogical to me: the device has rebooted uncounted times since then because it's not connected to permanent power.

**Comment by ckrey** [comment]
But the current time was 2002 ... While it still had power and current time there was no connection which led to the watchdog killing it after 6 minutes

**Comment by ckrey** [comment]
fixed: Hardware clock will now be set independent of the offUntil setting
